title = "Hackerlaan"
baseURL = "https://jrhackett.github.io/blog/"
languageCode = "en-us"
theme = ["https://github.com/nodejh/hugo-theme-mini"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 100
googleAnalytics = ""
enableRobotsTXT = true
